### ISSUE TITLE
姿态解算

### ISSUE THREAD

**Issue by daisenryaku** [xxyyttxx/Quadcopter#5]
[基于互补滤波的四元数姿态解算代码](http://bbs.loveuav.com/thread-382-1-1.html)
(1) short ax -> float ax ?
(2) Kp, Ki, halfT, 参数调节

**Comment by daisenryaku** [comment]
[MPU6050四元数解算求助](http://www.arduino.cn/forum.php?mod=viewthread&action=printable&tid=7621) 包含均值滤波
[多轴飞行器姿态的欧拉角算法](http://www.xi-chuang.com/?post=449) 给出逐行解释

**Comment by xxyyttxx** [comment]
转向硬解。
